<?php

namespace Database\Seeders;

use App\Models\LetterConfig;
use Illuminate\Database\Seeder;

class LetterConfigSeeder extends Seeder
{
    public function run(): void
    {
        $letters = [
            // ── Existing ──
            [
                'jenis_surat' => 'sktm',
                'label' => 'Surat Keterangan Tidak Mampu (SKTM)',
                'kode_klasifikasi' => '460',
                'masa_berlaku_bulan' => 3,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan dengan sesungguhnya bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nPekerjaan: {pekerjaan}\nAlamat: {alamat_lengkap}\n\nBerdasarkan data yang ada dan keterangan dari yang bersangkutan, bahwa nama tersebut di atas adalah warga yang kurang mampu / tidak mampu secara ekonomi. Penghasilan per bulan sebesar Rp {penghasilan}.\n\nSurat keterangan ini dibuat untuk keperluan: {alasan_sktm}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'select', 'required' => true, 'options' => 'Laki-laki,Perempuan', 'rules' => 'in:Laki-laki,Perempuan'],
                    ['key' => 'pekerjaan', 'label' => 'Pekerjaan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'penghasilan', 'label' => 'Penghasilan per Bulan (Rp)', 'type' => 'number', 'required' => true, 'rules' => 'numeric|min:0'],
                    ['key' => 'alasan_sktm', 'label' => 'Keperluan / Alasan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'agama', 'label' => 'Agama', 'type' => 'select', 'required' => false, 'options' => 'Islam,Kristen,Katolik,Hindu,Buddha,Konghucu', 'rules' => 'string|max:20'],
                    ['key' => 'status_perkawinan', 'label' => 'Status Perkawinan', 'type' => 'select', 'required' => false, 'options' => 'Belum Kawin,Kawin,Cerai Hidup,Cerai Mati', 'rules' => 'string|max:20'],
                    ['key' => 'kewarganegaraan', 'label' => 'Kewarganegaraan', 'type' => 'text', 'required' => false, 'rules' => 'string|max:50'],
                ],
            ],
            [
                'jenis_surat' => 'ktp_sementara',
                'label' => 'Surat Keterangan Pengganti KTP (Sementara)',
                'kode_klasifikasi' => '471',
                'masa_berlaku_bulan' => 1,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nPekerjaan: {pekerjaan}\nAlamat: {alamat_lengkap}\n\nBahwa yang bersangkutan sedang dalam proses pembuatan KTP Elektronik di Dinas Kependudukan dan Pencatatan Sipil. Surat keterangan ini berlaku sebagai pengganti KTP sementara.\n\nAlasan: {alasan_ktp}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'select', 'required' => true, 'options' => 'Laki-laki,Perempuan', 'rules' => 'in:Laki-laki,Perempuan'],
                    ['key' => 'pekerjaan', 'label' => 'Pekerjaan', 'type' => 'text', 'required' => false, 'rules' => 'string|max:50'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'alasan_ktp', 'label' => 'Alasan Pengajuan KTP Sementara', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'agama', 'label' => 'Agama', 'type' => 'select', 'required' => false, 'options' => 'Islam,Kristen,Katolik,Hindu,Buddha,Konghucu', 'rules' => 'string|max:20'],
                    ['key' => 'status_perkawinan', 'label' => 'Status Perkawinan', 'type' => 'select', 'required' => false, 'options' => 'Belum Kawin,Kawin,Cerai Hidup,Cerai Mati', 'rules' => 'string|max:20'],
                ],
            ],
            [
                'jenis_surat' => 'akta',
                'label' => 'Surat Pengantar Akta Kelahiran / Kematian',
                'kode_klasifikasi' => '472',
                'masa_berlaku_bulan' => 3,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nAlamat: {alamat_lengkap}\n\nBenar adalah warga Desa {nama_desa} yang mengajukan pembuatan {jenis_akta_label} untuk:\nNama: {nama_anak}\nTempat, Tgl Lahir: {tempat_lahir_anak}, {tgl_lahir_anak}\n\nSurat pengantar ini dibuat untuk keperluan pembuatan akta di Dinas Kependudukan dan Pencatatan Sipil.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap (Pemohon)', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK Pemohon', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Pemohon', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'jenis_akta', 'label' => 'Jenis Akta', 'type' => 'select', 'required' => true, 'options' => 'kelahiran,kematian', 'rules' => 'in:kelahiran,kematian'],
                    ['key' => 'nama_anak', 'label' => 'Nama Anak / Ahli Waris', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'tempat_lahir_anak', 'label' => 'Tempat Lahir Anak', 'type' => 'text', 'required' => false, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir_anak', 'label' => 'Tanggal Lahir Anak', 'type' => 'date', 'required' => false, 'rules' => 'date'],
                    ['key' => 'nama_ayah', 'label' => 'Nama Ayah', 'type' => 'text', 'required' => false, 'rules' => 'string|max:100'],
                    ['key' => 'nama_ibu', 'label' => 'Nama Ibu', 'type' => 'text', 'required' => false, 'rules' => 'string|max:100'],
                    ['key' => 'anak_ke', 'label' => 'Anak Ke-', 'type' => 'number', 'required' => false, 'rules' => 'integer|min:1'],
                ],
            ],

            // ── New Letter Types ──
            [
                'jenis_surat' => 'sku',
                'label' => 'Surat Keterangan Usaha (SKU)',
                'kode_klasifikasi' => '473',
                'masa_berlaku_bulan' => 6,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nAlamat: {alamat_lengkap}\n\nBenar memiliki usaha: {nama_usaha}\nBidang/Jenis Usaha: {bidang_usaha}\nBerlokasi di: {lokasi_usaha}\nSejak Tahun: {tahun_mulai}\n\nSurat keterangan ini dibuat untuk keperluan {keperluan_sku}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'nama_usaha', 'label' => 'Nama Usaha', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'bidang_usaha', 'label' => 'Bidang / Jenis Usaha', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'lokasi_usaha', 'label' => 'Lokasi Usaha', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'tahun_mulai', 'label' => 'Tahun Mulai Usaha', 'type' => 'number', 'required' => true, 'rules' => 'integer|min:1900|max:'.date('Y')],
                    ['key' => 'keperluan_sku', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'domisili',
                'label' => 'Surat Keterangan Domisili',
                'kode_klasifikasi' => '474',
                'masa_berlaku_bulan' => 12,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\n\nBenar berdomisili di alamat: {alamat_domisili}\nRT {rt_domisili} / RW {rw_domisili}, Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}.\n\nSurat keterangan domisili ini dibuat untuk keperluan: {keperluan_domisili}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'alamat_domisili', 'label' => 'Alamat Domisili (Lengkap)', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'rt_domisili', 'label' => 'RT', 'type' => 'text', 'required' => true, 'rules' => 'string|max:3'],
                    ['key' => 'rw_domisili', 'label' => 'RW', 'type' => 'text', 'required' => true, 'rules' => 'string|max:3'],
                    ['key' => 'keperluan_domisili', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'skkb',
                'label' => 'Surat Keterangan Kelakuan Baik (SKKB)',
                'kode_klasifikasi' => '475',
                'masa_berlaku_bulan' => 6,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nAlamat: {alamat_lengkap}\n\nBerdasarkan data dan informasi yang kami ketahui, nama tersebut di atas selama berdomisili di wilayah Desa {nama_desa} berkelakuan baik, tidak pernah terlibat tindak pidana, dan tidak tercatat dalam daftar gangguan keamanan dan ketertiban masyarakat.\n\nSurat keterangan ini dibuat untuk keperluan: {keperluan_skkb}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'select', 'required' => true, 'options' => 'Laki-laki,Perempuan', 'rules' => 'in:Laki-laki,Perempuan'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'pekerjaan', 'label' => 'Pekerjaan', 'type' => 'text', 'required' => false, 'rules' => 'string|max:50'],
                    ['key' => 'keperluan_skkb', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'belum_menikah',
                'label' => 'Surat Keterangan Belum Menikah',
                'kode_klasifikasi' => '476',
                'masa_berlaku_bulan' => 3,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nJenis Kelamin: {jenis_kelamin_label}\nPekerjaan: {pekerjaan}\nAlamat: {alamat_lengkap}\n\nBerdasarkan data dan keterangan yang kami peroleh, bahwa nama tersebut di atas benar-benar belum pernah menikah / masih lajang menurut catatan kami.\n\nSurat keterangan ini dibuat untuk keperluan: {keperluan_belum_menikah}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'select', 'required' => true, 'options' => 'Laki-laki,Perempuan', 'rules' => 'in:Laki-laki,Perempuan'],
                    ['key' => 'pekerjaan', 'label' => 'Pekerjaan', 'type' => 'text', 'required' => false, 'rules' => 'string|max:50'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'keperluan_belum_menikah', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'izin_keramaian',
                'label' => 'Surat Izin Keramaian',
                'kode_klasifikasi' => '477',
                'masa_berlaku_bulan' => 0,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, memberikan izin kepada:\n\nNama: {nama_lengkap}\nNIK: {nik}\nAlamat: {alamat_lengkap}\n\nUntuk menyelenggarakan kegiatan:\nNama Kegiatan: {nama_kegiatan}\nJenis Kegiatan: {jenis_kegiatan}\nTanggal Pelaksanaan: {tgl_kegiatan}\nLokasi: {lokasi_kegiatan}\nJumlah Peserta: {jumlah_peserta} orang\n\nDengan ketentuan wajib menjaga ketertiban dan keamanan serta bertanggung jawab penuh atas kelancaran kegiatan.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap (Penanggung Jawab)', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'nama_kegiatan', 'label' => 'Nama Kegiatan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:200'],
                    ['key' => 'jenis_kegiatan', 'label' => 'Jenis Kegiatan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'tgl_kegiatan', 'label' => 'Tanggal Pelaksanaan', 'type' => 'date', 'required' => true, 'rules' => 'date|after:today'],
                    ['key' => 'lokasi_kegiatan', 'label' => 'Lokasi Kegiatan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'jumlah_peserta', 'label' => 'Jumlah Peserta (perkiraan)', 'type' => 'number', 'required' => true, 'rules' => 'integer|min:1|max:50000'],
                    ['key' => 'jam_mulai', 'label' => 'Jam Mulai', 'type' => 'time', 'required' => false, 'rules' => 'string'],
                    ['key' => 'jam_selesai', 'label' => 'Jam Selesai', 'type' => 'time', 'required' => false, 'rules' => 'string'],
                ],
            ],
            [
                'jenis_surat' => 'ahli_waris',
                'label' => 'Surat Keterangan Ahli Waris',
                'kode_klasifikasi' => '478',
                'masa_berlaku_bulan' => 0,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nAhli waris dari almarhum/almarhumah:\nNama Pewaris: {nama_pewaris}\nNIK Pewaris: {nik_pewaris}\nAlamat Pewaris: {alamat_pewaris}\nMeninggal pada: {tgl_meninggal}\n\nAdalah:\n\nNama: {nama_lengkap}\nNIK: {nik}\nHubungan: {hubungan_ahli_waris}\nAlamat: {alamat_lengkap}\n\nSurat keterangan ini dibuat untuk keperluan: {keperluan_ahli_waris}.",
                'fields' => [
                    ['key' => 'nama_pewaris', 'label' => 'Nama Pewaris (Almarhum)', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik_pewaris', 'label' => 'NIK Pewaris', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'alamat_pewaris', 'label' => 'Alamat Pewaris', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'tgl_meninggal', 'label' => 'Tanggal Meninggal', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap (Ahli Waris)', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK Ahli Waris', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'hubungan_ahli_waris', 'label' => 'Hubungan dengan Pewaris', 'type' => 'select', 'required' => true, 'options' => 'Suami,Istri,Anak Kandung,Anak Angkat,Orang Tua,Saudara Kandung,Lainnya', 'rules' => 'string|max:50'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Ahli Waris', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'keperluan_ahli_waris', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'kepemilikan_tanah',
                'label' => 'Surat Keterangan Kepemilikan Tanah',
                'kode_klasifikasi' => '479',
                'masa_berlaku_bulan' => 0,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nAlamat: {alamat_lengkap}\n\nBenar memiliki sebidang tanah yang terletak di:\nLokasi: {lokasi_tanah}\nLuas: {luas_tanah} m²\nBatas Utara: {batas_utara}\nBatas Selatan: {batas_selatan}\nBatas Timur: {batas_timur}\nBatas Barat: {batas_barat}\n\nTanah tersebut dikuasai secara sah dan tidak dalam sengketa dengan pihak lain. Surat ini dibuat untuk keperluan: {keperluan_tanah}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap (Pemilik)', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'lokasi_tanah', 'label' => 'Lokasi Tanah', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'luas_tanah', 'label' => 'Luas Tanah (m²)', 'type' => 'number', 'required' => true, 'rules' => 'numeric|min:1'],
                    ['key' => 'batas_utara', 'label' => 'Batas Utara', 'type' => 'text', 'required' => true, 'rules' => 'string|max:200'],
                    ['key' => 'batas_selatan', 'label' => 'Batas Selatan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:200'],
                    ['key' => 'batas_timur', 'label' => 'Batas Timur', 'type' => 'text', 'required' => true, 'rules' => 'string|max:200'],
                    ['key' => 'batas_barat', 'label' => 'Batas Barat', 'type' => 'text', 'required' => true, 'rules' => 'string|max:200'],
                    ['key' => 'keperluan_tanah', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'pengantar_skck',
                'label' => 'Surat Pengantar SKCK',
                'kode_klasifikasi' => '480',
                'masa_berlaku_bulan' => 3,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nJenis Kelamin: {jenis_kelamin_label}\nPekerjaan: {pekerjaan}\nAlamat: {alamat_lengkap}\n\nBahwa yang bersangkutan berkelakuan baik dan tidak pernah tersangkut perkara pidana. Surat pengantar ini dibuat untuk keperluan pembuatan SKCK di Kepolisian Sektor {kecamatan}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'select', 'required' => true, 'options' => 'Laki-laki,Perempuan', 'rules' => 'in:Laki-laki,Perempuan'],
                    ['key' => 'pekerjaan', 'label' => 'Pekerjaan', 'type' => 'text', 'required' => false, 'rules' => 'string|max:50'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'agama', 'label' => 'Agama', 'type' => 'select', 'required' => false, 'options' => 'Islam,Kristen,Katolik,Hindu,Buddha,Konghucu', 'rules' => 'string|max:20'],
                ],
            ],
            [
                'jenis_surat' => 'penghasilan',
                'label' => 'Surat Keterangan Penghasilan',
                'kode_klasifikasi' => '481',
                'masa_berlaku_bulan' => 3,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nPekerjaan: {pekerjaan}\nAlamat: {alamat_lengkap}\n\nBenar memiliki penghasilan tetap sebesar Rp {jumlah_penghasilan} per {periode_penghasilan} sebagai {sumber_penghasilan}.\n\nSurat keterangan penghasilan ini dibuat untuk keperluan: {keperluan_penghasilan}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'pekerjaan', 'label' => 'Pekerjaan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'jumlah_penghasilan', 'label' => 'Jumlah Penghasilan (Rp)', 'type' => 'number', 'required' => true, 'rules' => 'numeric|min:0'],
                    ['key' => 'periode_penghasilan', 'label' => 'Periode Penghasilan', 'type' => 'select', 'required' => true, 'options' => 'hari,minggu,bulan,tahun', 'rules' => 'in:hari,minggu,bulan,tahun'],
                    ['key' => 'sumber_penghasilan', 'label' => 'Sumber Penghasilan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:200'],
                    ['key' => 'keperluan_penghasilan', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'janda_duda',
                'label' => 'Surat Keterangan Janda / Duda',
                'kode_klasifikasi' => '482',
                'masa_berlaku_bulan' => 6,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nJenis Kelamin: {jenis_kelamin_label}\nAlamat: {alamat_lengkap}\n\nBenar berstatus {status_janda_label} karena {penyebab_janda} pada tanggal {tgl_janda} dan sampai saat ini belum menikah lagi.\n\nSurat keterangan ini dibuat untuk keperluan: {keperluan_janda}.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'jenis_kelamin', 'label' => 'Jenis Kelamin', 'type' => 'select', 'required' => true, 'options' => 'Laki-laki,Perempuan', 'rules' => 'in:Laki-laki,Perempuan'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Lengkap', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'penyebab_janda', 'label' => 'Penyebab (Meninggal / Cerai)', 'type' => 'select', 'required' => true, 'options' => 'Meninggal Dunia,Cerai', 'rules' => 'string|max:50'],
                    ['key' => 'tgl_janda', 'label' => 'Tanggal Kejadian', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'keperluan_janda', 'label' => 'Keperluan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
            [
                'jenis_surat' => 'pindah',
                'label' => 'Surat Keterangan Pindah',
                'kode_klasifikasi' => '483',
                'masa_berlaku_bulan' => 1,
                'body_template' => "Yang bertanda tangan di bawah ini, {jabatan_kades}, Kepala Desa {nama_desa}, Kecamatan {kecamatan}, Kabupaten {kabupaten}, menerangkan bahwa:\n\nNama: {nama_lengkap}\nNIK: {nik}\nTempat, Tgl Lahir: {tempat_lahir}, {tgl_lahir}\nAlamat Asal: {alamat_lengkap}\n\nBenar akan pindah ke:\nAlamat Tujuan: {alamat_tujuan}\nDesa/Kelurahan: {desa_tujuan}\nKecamatan: {kecamatan_tujuan}\nKabupaten/Kota: {kabupaten_tujuan}\nProvinsi: {provinsi_tujuan}\n\nAlasan pindah: {alasan_pindah}.\n\nSurat keterangan pindah ini dibuat untuk keperluan administrasi kependudukan.",
                'fields' => [
                    ['key' => 'nama_lengkap', 'label' => 'Nama Lengkap', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'nik', 'label' => 'NIK', 'type' => 'text', 'required' => true, 'rules' => 'string|size:16'],
                    ['key' => 'tempat_lahir', 'label' => 'Tempat Lahir', 'type' => 'text', 'required' => true, 'rules' => 'string|max:50'],
                    ['key' => 'tgl_lahir', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true, 'rules' => 'date'],
                    ['key' => 'alamat_lengkap', 'label' => 'Alamat Asal', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'alamat_tujuan', 'label' => 'Alamat Tujuan', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                    ['key' => 'desa_tujuan', 'label' => 'Desa / Kelurahan Tujuan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'kecamatan_tujuan', 'label' => 'Kecamatan Tujuan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'kabupaten_tujuan', 'label' => 'Kabupaten / Kota Tujuan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'provinsi_tujuan', 'label' => 'Provinsi Tujuan', 'type' => 'text', 'required' => true, 'rules' => 'string|max:100'],
                    ['key' => 'alasan_pindah', 'label' => 'Alasan Pindah', 'type' => 'textarea', 'required' => true, 'rules' => 'string|max:500'],
                ],
            ],
        ];

        foreach ($letters as $letter) {
            LetterConfig::updateOrCreate(
                ['jenis_surat' => $letter['jenis_surat']],
                $letter + ['is_active' => true]
            );
        }
    }
}
